steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world
  - --source=https://github.com/aseemgupta02/cloudbuildtest/blob/master/function-source.zip
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
