steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world
  - --source=/cloudbuild/function-source.zip
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
